Bebop-Web/src/main/java/fr/eql/ai110/bebop/controller/ArchetypeManagedBean.java
package fr.eql.ai110.bebop.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import fr.eql.ai110.bebop.entity.ArchetypeEntity;
import fr.eql.ai110.bebop.ibusiness.ArchetypeIBusiness;

@ManagedBean(name="mbArchetype")
@SessionScoped
public class ArchetypeManagedBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private ArchetypeIBusiness archetypeBusiness;

	//ATTRIBUTES
	private String name;
	private String message;
	private ArchetypeEntity archetypeEntity;
	private List<ArchetypeEntity> archetypeEntities;

	private Integer idBuffer;	//Temporarily stores the Id of a Unique Selection, useful for a quick Update or Delete operation


	//METHODS
	@PostConstruct
	public void init() {
		getArchetypes();
	}

	public void getArchetypes() {
		archetypeEntities = archetypeBusiness.findAllArchetypeEntities();
		if (message==null) createMessage(archetypeEntities.size()>0);
	}

	public String createMessage(boolean myCondition) {
		if (myCondition) {
			message = archetypeEntities.size() + " archetype(s) found";
		} else {
			message = "Woops nothing there";
		}
		return message;
	}

	//Create
	public String createOneArchetype() {
		archetypeEntity = new ArchetypeEntity();
		archetypeEntity.setName(name);
		boolean verify = archetypeBusiness.createArchetypeEntity(archetypeEntity);
		if (verify) {
			message = name + " was successfully created";
		} else {
			message = name + " is already taken";
		}
		getArchetypes();
		return message;
	}

	//Read
	public void searchAllArchetypesByName() {
		archetypeEntities = archetypeBusiness.findArchetypeEntitiesByName(name);
		createMessage(archetypeEntities.size()>0);
		if (archetypeEntities.size()==1) {
			idBuffer = archetypeEntities.get(0).getId();
		} else {
			idBuffer = null;
		}
	}

	public void searchOneArchetypeById() {
		archetypeEntity = null;
		try {
			Integer id = Integer.parseInt(name);
			archetypeEntity = archetypeBusiness.findArchetypeEntityById(id);
		} catch (Exception e) {
			e.printStackTrace();
		} 
		if (archetypeEntity!=null) {
			archetypeEntities = new ArrayList<ArchetypeEntity>();
			archetypeEntities.add(archetypeEntity); 
			idBuffer = archetypeEntities.get(0).getId();	//Can only every return a single element
		} else {
			archetypeEntities.clear();
		}
		createMessage(archetypeEntities.size()>0);
	}

	//Update
	public String modifyOneArchetype() {
		if (idBuffer!=null) {
			archetypeEntity.setId(idBuffer);
			archetypeEntity.setName(name);
			boolean verify = archetypeBusiness.updateArchetypeEntity(archetypeEntity);
			if (verify) {
				message = "Was successfully updated to " + name;
			} else {
				message = name + " is already taken";
			}
			idBuffer = null;
			getArchetypes();
		} else {
			searchAllArchetypesByName();
			name = "";
			message = "please select a single archetype to update";
		}
		return message;
	}

	//Remove
	public String removeArchetype() {
		if (idBuffer!=null) {
			archetypeEntity.setId(idBuffer);
			boolean verify = archetypeBusiness.deleteArchetypeEntity(archetypeEntity);
			if (verify) {
				message = "Successfully deleted";
			} else {
				message = "May no longer exist";
			}
			idBuffer = null;
			getArchetypes();
		} else {
			searchAllArchetypesByName();
			name = "";
			message = "please select a single archetype to delete";
		}
		return message;
	}


	//GETTERS & SETTERS
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public ArchetypeEntity getArchetypeEntity() {
		return archetypeEntity;
	}

	public void setArchetypeEntity(ArchetypeEntity archetypeEntity) {
		this.archetypeEntity = archetypeEntity;
	}

	public List<ArchetypeEntity> getArchetypeEntities() {
		return archetypeEntities;
	}

	public void setArchetypeEntities(List<ArchetypeEntity> archetypeEntities) {
		this.archetypeEntities = archetypeEntities;
	}

	public Integer getIdBuffer() {
		return idBuffer;
	}

	public void setIdBuffer(Integer idBuffer) {
		this.idBuffer = idBuffer;
	}

}

Bebop-Web/src/main/java/fr/eql/ai110/bebop/controller/AuthenticationManagedBean.java
package fr.eql.ai110.bebop.controller;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.eql.ai110.bebop.entity.Admin;
import fr.eql.ai110.bebop.entity.City;
import fr.eql.ai110.bebop.entity.Client;
import fr.eql.ai110.bebop.entity.Partner;
import fr.eql.ai110.bebop.ibusiness.AdminIBusiness;
import fr.eql.ai110.bebop.ibusiness.CityIBusiness;
import fr.eql.ai110.bebop.ibusiness.ClientIBusiness;
import fr.eql.ai110.bebop.ibusiness.PartnerIBusiness;
import net.bootsfaces.utils.FacesMessages;

@ManagedBean(name="mbAuthentication")
@SessionScoped
public class AuthenticationManagedBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private AdminIBusiness adminBusiness;

	@EJB
	private PartnerIBusiness partnerBusiness;

	@EJB
	private ClientIBusiness clientBusiness;

	@EJB
	private CityIBusiness cityBusiness;



	// ***** ATTRIBUTES *****

	//Partner

	private LocalDate partnerBirthdate;
	private String partnerDescription;
	private String partnerEmail;
	private String partnerFirstName;
	private String partnerLastName;
	private String partnerOrganization;
	private String partnerPassword;
	private String partnerPhone;
	private String partnerPicture;
	private String partnerTitle;
	private String partnerUsername;
	private String partnerValidationCode;
	private Integer partnerCityFK;

	//Client

	private LocalDate clientBirthdate;
	private String clientEmail;
	private String clientFirstName;
	private String clientLastName;
	private String clientPassword;
	private String clientPhone;
	private Integer clientPoints;
	private String clientUsername;
	private String clientValidationCode;
	private Integer clientCityFK;

	private String dateConvert;	//Stores the date entered as string ready for parsing in dateTransform(String date)

	private Admin admin; 
	private Partner partner;
	private Client client;

	private String username;
	private String password;

	private String loggedUser;

	private City city;
	private List<City> cities;

	private String clientMessage;
	private String partnerMessage;



	// ***** METHODS *****

	@PostConstruct
	public void init() {
		getAllCities();
	}

	public void getAllCities() {
		cities = cityBusiness.findAllCities();
	}

	private LocalDate dateTransform(String date) {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/MM/yyyy");
		LocalDate localDate = null;
		if (dateConvert.length()==10) {
			localDate = LocalDate.parse(date,formatter);

		}
		return localDate;
	}

	private void clearFields() {
		username = null;
		password = null;
	}



	// *** CREATE ***

	public String createPartner() {
		String forward = "/login.xhtml?faces-redirection=true";
		Partner partner = new Partner();
		partnerBirthdate = dateTransform(dateConvert);
		partner.setBirthdate(partnerBirthdate);
		partner.setCity(cityBusiness.findCityById(partnerCityFK));
		partner.setCreateTime(LocalDateTime.now());
		partner.setDescription(partnerDescription);
		partner.setEmail(partnerEmail);
		partner.setFirstName(partnerFirstName);
		partner.setLastName(partnerLastName);
		partner.setOrganization(partnerOrganization);
		partner.setPassword(partnerPassword);
		partner.setPhone(partnerPhone);
		partner.setPicture(partnerPicture);
		partner.setTitle(partnerTitle);
		partner.setUsername(partnerUsername);
		partner.setValidationCode(partnerValidationCode);
		boolean verify = partnerBusiness.createPartner(partner);	
		if (verify) {
			FacesMessages.info("Votre compte " + partnerUsername + " a bien été créé :) ");
		} else {
			FacesMessages.warning("Oups c'est déjà pris ou les champs ne sont pas respectés :O");
			forward = null;
		} 
		return forward;
	}

	public String createClient() {
		String forward = "/login.xhtml?faces-redirection=true";
		Client client = new Client();
		clientBirthdate = dateTransform(dateConvert);
		client.setBirthdate(clientBirthdate);
		client.setCity(cityBusiness.findCityById(clientCityFK));
		client.setCreateTime(LocalDateTime.now());
		client.setEmail(clientEmail);
		client.setFirstName(clientFirstName);
		client.setLastName(clientLastName);
		client.setPassword(clientPassword);
		client.setPhone(clientPhone);
		client.setPoints(clientPoints);
		client.setUsername(clientUsername);
		client.setValidationCode(clientValidationCode);
		boolean verify = clientBusiness.createClient(client);
		if (verify) {
			FacesMessages.info("Votre compte " + clientUsername + " a bien été créé :) ");
		} else {
			FacesMessages.warning("Oups c'est déjà pris ou les champs ne sont pas respectés :O");
			forward = null;
		}
		return forward;
	}



	// *** CONNECT ***

	public String connectUser() {
		String forward = null;
		
		if (username.length()>1) {
			Admin myAdmin = new Admin();
			myAdmin.setUsername(username);
			myAdmin.setPassword(password);
			admin = adminBusiness.connectAdmin(myAdmin);

			Partner myPartner = new Partner();
			myPartner.setUsername(username);
			myPartner.setPassword(password);
			partner = partnerBusiness.connectPartner(myPartner);

			Client myClient = new Client();
			myClient.setUsername(username);
			myClient.setPassword(password);
			client = clientBusiness.connectClient(myClient);

			if (isAdminConnected()) {
				loggedUser = " : " + admin.getUsername() + " [Admin]";
				FacesMessages.info("Bonjour " + admin.getUsername() + " :) ");
				forward = "/admin-operations.xhtml?faces-redirection=false";
			} else if (isPartnerConnected()) {
				loggedUser = " : " + partner.getUsername() + " [Partner]";
				FacesMessages.info("Bonjour " + partner.getUsername() + " :) ");
				forward = "/home.xhtml?faces-redirection=true";
			} else if (isClientConnected()) {
				loggedUser = " : " + client.getUsername();
				FacesMessages.info("Bonjour " + client.getUsername() + " :) ");
				forward = "/home.xhtml?faces-redirection=true";
			} else {
				FacesMessages.warning("Votre identifiant ou mot de passe est incorrect :O");
				forward = "/login.xhtml?faces-redirection=false";
			}
		} else {
			FacesMessages.info("Veuillez rentrer votre identifiant et mot de passe");
		}
		
		return forward;
	}

	public boolean isUserConnected() {
		return (isAdminConnected()||isPartnerConnected()||isClientConnected());
	}

	public boolean isAdminConnected() {
		boolean verify = false;
		if (admin!=null) {
			verify = true;
		}
		return verify;
	}

	public boolean isPartnerConnected() {
		boolean verify = false;
		if (partner!=null) {
			verify = true;
		}
		return verify;
	}

	public boolean isClientConnected() {
		boolean verify = false;
		if (client!=null) {
			verify = true;
		}
		return verify;
	}

	// *** DISCONNECT ***

	public String disconnect() {
		if (isUserConnected()) FacesMessages.info("A bientôt ! ");
		HttpSession session = (HttpSession) FacesContext
				.getCurrentInstance()
				.getExternalContext()
				.getSession(true);
		session.invalidate();
		admin = null;
		partner = null;
		client = null;
		loggedUser = null;
		clearFields();
		return "/login.xhtml?faces-redirection=true";
	}



	// ***** GETTERS & SETTERS *****

	public LocalDate getPartnerBirthdate() {
		return partnerBirthdate;
	}

	public void setPartnerBirthdate(LocalDate partnerBirthdate) {
		this.partnerBirthdate = partnerBirthdate;
	}

	public String getPartnerDescription() {
		return partnerDescription;
	}

	public void setPartnerDescription(String partnerDescription) {
		this.partnerDescription = partnerDescription;
	}

	public String getPartnerEmail() {
		return partnerEmail;
	}

	public void setPartnerEmail(String partnerEmail) {
		this.partnerEmail = partnerEmail;
	}

	public String getPartnerFirstName() {
		return partnerFirstName;
	}

	public void setPartnerFirstName(String partnerFirstName) {
		this.partnerFirstName = partnerFirstName;
	}

	public String getPartnerLastName() {
		return partnerLastName;
	}

	public void setPartnerLastName(String partnerLastName) {
		this.partnerLastName = partnerLastName;
	}

	public String getPartnerOrganization() {
		return partnerOrganization;
	}

	public void setPartnerOrganization(String partnerOrganization) {
		this.partnerOrganization = partnerOrganization;
	}

	public String getPartnerPassword() {
		return partnerPassword;
	}

	public void setPartnerPassword(String partnerPassword) {
		this.partnerPassword = partnerPassword;
	}

	public String getPartnerPhone() {
		return partnerPhone;
	}

	public void setPartnerPhone(String partnerPhone) {
		this.partnerPhone = partnerPhone;
	}

	public String getPartnerPicture() {
		return partnerPicture;
	}

	public void setPartnerPicture(String partnerPicture) {
		this.partnerPicture = partnerPicture;
	}

	public String getPartnerTitle() {
		return partnerTitle;
	}

	public void setPartnerTitle(String partnerTitle) {
		this.partnerTitle = partnerTitle;
	}

	public String getPartnerUsername() {
		return partnerUsername;
	}

	public void setPartnerUsername(String partnerUsername) {
		this.partnerUsername = partnerUsername;
	}

	public String getPartnerValidationCode() {
		return partnerValidationCode;
	}

	public void setPartnerValidationCode(String partnerValidationCode) {
		this.partnerValidationCode = partnerValidationCode;
	}

	public Integer getPartnerCityFK() {
		return partnerCityFK;
	}

	public void setPartnerCityFK(Integer partnerCityFK) {
		this.partnerCityFK = partnerCityFK;
	}

	public LocalDate getClientBirthdate() {
		return clientBirthdate;
	}

	public void setClientBirthdate(LocalDate clientBirthdate) {
		this.clientBirthdate = clientBirthdate;
	}

	public String getClientEmail() {
		return clientEmail;
	}

	public void setClientEmail(String clientEmail) {
		this.clientEmail = clientEmail;
	}

	public String getClientFirstName() {

Bebop-Web/src/main/webapp/arch2.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<h:head>
	<ui:insert name="head"></ui:insert>
	<h:outputStylesheet library="css" name="style.css" position="last" />
	<link rel="icon" type="image/png"
		href="#{request.contextPath}/resources/pictures/logo.ico" />
</h:head>

<h:body style="background-color:gray;color:snow">
	<b:navBar brand-style-class="navbarTitle"
		brand="Be Box Office Planet  #{mbAuthentication.loggedUser}"
		brand-img="#{request.contextPath}/resources/pictures/logo.png"
		brand-img-style-class="logoNavbar" brandHref="home.xhtml">

		<b:navbarLinks pull="right">
			<b:navLink class="navbarItems" value="Evenements" href="events.xhtml" />
			<b:navLink class="navbarItems" value="Partenaires"
				href="partners.xhtml" />
			<b:navLink class="navbarItems" value="Récompenses"
				href="rewards.xhtml" />
			
			<b:navLink value="Administration" icon-awesome="users"
				href="admin-operations.xhtml"
				rendered="#{mbAuthentication.adminConnected}" />
			
			<b:navLink value="Mes événéments" icon-awesome="ticket"
				href="partner-events.xhtml"
				rendered="#{mbAuthentication.partnerConnected}" />
			<b:navLink value="Mon box office" icon-awesome="rocket"
				href="box-office.xhtml"
				rendered="#{mbAuthentication.partnerConnected}" />
			
			<b:navLink value="Mes billets" icon-awesome="ticket"
				href="my-tickets.xhtml"
				rendered="#{mbAuthentication.clientConnected}" />
			<b:navLink value="Ma wishlist" icon-awesome="star"
				href="my-wishlist.xhtml"
				rendered="#{mbAuthentication.clientConnected}" />
			<b:navLink value="Mon panier" icon-awesome="cart-plus"
				href="checkout-basket.xhtml"
				rendered="#{mbAuthentication.clientConnected}" />
			<b:navLink value="Mes récompenses" icon-awesome="trophy"
				href="my-rewards.xhtml"
				rendered="#{mbAuthentication.clientConnected}" />
			
			<b:navLink class="navbarItems" value="Connexion" icon-awesome="key"
				href="login.xhtml" action="#{mbAuthenticationS}" />
			<b:navLink class="navbarItems" value="Mon compte"
				icon-awesome="wrench" href="user-settings.xhtml"
				rendered="#{mbAuthentication.userConnected}" />
		</b:navbarLinks>
	</b:navBar>
	
	<b:container style="min-height: calc(100vh - 17.2rem)">
		<b:row>
			<b:column style-class="bebop-content">
				<ui:insert name="content"></ui:insert>
			</b:column>
		</b:row>
	</b:container>
	
	<b:growl id="growl" allow-dismiss="true" globalOnly="true"
		showDetail="true" severity="info,warn,error" placementFrom="bottom"
		animation-enter="animated slideInDown"
		animation-exit="animated fadeOutDown" />

	<div
		class="bebop-footer bebop-flex-justify-content bebop-flex-align-items">
		<a style="color: black;" href="privacy.xhtml"><h4>BeBOP -
				2022</h4>
			<h5 style="font-style: italic;">à propos</h5></a>
	</div>
</h:body>

</html>

Bebop-Web/src/main/webapp/archetype.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Archetype Page</title>
	</ui:define>

	<ui:define name="content">

		<b:panel title="List of archetypes">
			<h:outputLabel value="Controller message : #{mbArchetype.message}" />
			<ui:repeat value="#{mbArchetype.archetypeEntities}" var="archetype">
				<br />
				<h:outputLabel value="name : #{archetype.name} id : #{archetype.id}" />
			</ui:repeat>
		</b:panel>

		<b:form id="archetypeForm">
			<b:panel>
				<b:row>
					<b:column
						style-class="hidden-xs bebop-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
						<h:outputText value="Name" />
					</b:column>
					<b:column
						style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
						<h:outputText value="Name" />
					</b:column>
					<b:column
						style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
						<b:inputText id="archetypeName" placeholder="Enter a name"
							onfocus="this.value=''" value="#{mbArchetype.name}">
						</b:inputText>
					</b:column>
				</b:row>
				<b:row>
					<b:column
						style-class="bebop-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="bebop-width-100" value="Search"
							action="#{mbArchetype.searchAllArchetypesByName()}" />
					</b:column>
					<b:column
						style-class="bebop-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="bebop-width-100" value="Create"
							action="#{mbArchetype.createOneArchetype()}" />
					</b:column>
					<b:column
						style-class="bebop-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="bebop-width-100" value="Modify"
							action="#{mbArchetype.modifyOneArchetype()}" />
					</b:column>
					<b:column
						style-class="bebop-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="bebop-width-100" value="Remove"
							action="#{mbArchetype.removeArchetype()}" />
					</b:column>
					<b:column
						style-class="bebop-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="bebop-width-100" value="SearchID"
							action="#{mbArchetype.searchOneArchetypeById()}" />
					</b:column>
				</b:row>
			</b:panel>

		</b:form>

	</ui:define>
</ui:composition>

</html>

Bebop-Web/src/main/webapp/box-office.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Mes billets</title>
	</ui:define>

	<ui:define name="content">
		<b:form>
			<b:panel
				style-class="col-sm-offset-0 col-md-offset-0 col-xs-12 col-sm-12 col-md-12">
				<b:row>
					<h3>Mon Box Office</h3>
				</b:row>
				<h1 style="font-style: italic">Dashboard</h1>
				<b:row>
					<h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
						Duis nulla elit, mollis eu accumsan ut, tincidunt et lectus.
						Pellentesque ut risus non ex venenatis auctor ac elementum purus.
						Sed dapibus mattis ipsum at eleifend. Cras sit amet pulvinar arcu.
						Curabitur et tellus eget elit lacinia hendrerit ac et risus.
						Suspendisse varius, nisi mollis rutrum feugiat, magna lectus
						finibus erat, aliquam hendrerit libero magna tristique sem. Mauris
						id sem ultricies felis vehicula mattis sed non mauris. Aenean
						accumsan accumsan arcu, ut tempor massa molestie in. Integer vel
						lobortis neque. In in nibh sit amet augue placerat fermentum eu
						eget est.</h4>
				</b:row>
			</b:panel>
		</b:form>
	</ui:define>
</ui:composition>

</html>

Bebop-Web/src/main/webapp/checkout-basket.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Mes billets</title>
	</ui:define>

	<ui:define name="content">
		<b:form>
			<b:panel
				style-class="col-sm-offset-0 col-md-offset-0 col-xs-12 col-sm-12 col-md-12">
				<b:row>
					<h3>Mon panier</h3>
				</b:row>
				<b:row>
					<h4>In id facilisis nisi. Cras sed risus enim. In condimentum
						pretium velit, et porta felis mattis sed. Aenean posuere purus
						magna, a efficitur sapien faucibus ut. Donec mollis, odio id
						efficitur condimentum, lacus nulla sollicitudin ipsum, nec
						volutpat massa urna eget leo. Ut sed tortor ut turpis sagittis
						vulputate. Cras tristique massa massa, eget tincidunt enim
						ultrices eu. Aliquam pellentesque condimentum tortor, ultricies
						egestas orci dapibus non. Vivamus vel augue feugiat, ullamcorper
						erat ut, euismod elit.</h4>
				</b:row>
			</b:panel>
		</b:form>
	</ui:define>
</ui:composition>

</html>

Bebop-Web/src/main/webapp/privacy.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>BeBOP à propos</title>
	</ui:define>

	<ui:define name="content">
		<b:form>
			<b:panel
				style-class="col-sm-offset-0 col-md-offset-0 col-xs-12 col-sm-12 col-md-12">
				<b:row>
					<h3 style="font-style: italic">à propos de BeBOP</h3>
				</b:row>
				<b:row>
					<h4>Son idée fédératrice est de soutenir la culture d’une part en facilitant les réservations de places depuis une même plateforme, mais aussi en mettant à disposition aux professionnels des métiers du spectacle un outil leur permettant de créer leur propre billetterie en ligne.</h4>
				</b:row>
			</b:panel>
		</b:form>
	</ui:define>
</ui:composition>

</html>